apiVersion: v1
kind: Secret
metadata:
  name: mysqldump-secret
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  dbhost: {{ .Values.secret.dbhost | b64enc }}
  dbport: {{ .Values.secret.dbport | b64enc }}
  dbuser: {{ .Values.secret.dbuser | b64enc }}
  dbpass: {{ .Values.secret.dbpass | b64enc }}
